name: Manual build signed Nudge and upload signed package

env:
  NOTARY_APP_PASSWORD: ${{ secrets.NOTARY_APP_PASSWORD }}

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Checkout nudge repo
      uses: actions/checkout@v3.2.0
      with:
        fetch-depth: 0

    - name: Install Apple Xcode certificates
      uses: ssrobins/import-codesign-certs@04ce695a5e6002f1971a8ed78fedd676318f950f # Move back to apple-actions/import-codesign-certs when merged
      with:
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        p12-file-base64: ${{ secrets.APP_CERTIFICATES_P12 }}
        p12-password: ${{ secrets.APP_CERTIFICATES_P12_PASSWORD }}

    - name: Install Apple Installer certificates
      uses: ssrobins/import-codesign-certs@04ce695a5e6002f1971a8ed78fedd676318f950f # Move back to apple-actions/import-codesign-certs when merged
      with:
        create-keychain: false # do not create a new keychain for this value
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        p12-file-base64: ${{ secrets.PKG_CERTIFICATES_P12 }}
        p12-password: ${{ secrets.PKG_CERTIFICATES_P12_PASSWORD }}

    - name: Run build package script
      run: ./build_nudge.zsh "CREATE_PKG" "$NOTARY_APP_PASSWORD"

    - name: get environment variables
      id: get_env_var
      run: |
         echo "NUDGE_VERSION=$(/bin/cat ./build_info.txt)" >> $GITHUB_ENV
         echo "NUDGE_MAIN_VERSION=$(/bin/cat ./build_info_main.txt)" >> $GITHUB_ENV

    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@b97ce03a10d9bdbb07beb491c76a5a01d78cd3ef # v2.2.2
      with:
        validation_depth: 100
        version: ${{ env.NUDGE_MAIN_VERSION }}

    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@31b6d6f9e6e17e84ad34bee780f82d8ee79f6842 # v4.0.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        reverse: 'true'

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      with:
        name: v${{env.NUDGE_VERSION}}
        tag_name: v${{env.NUDGE_VERSION}}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
            # Notes
            This is a version of Nudge created by GitHub Actions.
            Nudge.app has been signed and notarized. The package has been signed, notarized and stapled.

            By default Nudge looks for a `com.github.macadmins.Nudge.json` file located in `/Library/Preferences`. If you would like to use an alternative path, please read the [README](https://github.com/macadmins/nudge/blob/main/README.md) or the [WIKI](https://github.com/macadmins/nudge/wiki)

            ## About the LaunchAgent
            This is a basic launch agent that opens Nudge twice an hour, every 30 minutes.
            If you would like to reduce the amount of times Nudge launches per day, it is recommended to create your own LaunchAgent.

            # Changelog
            ${{ steps.changelog_reader.outputs.changes }}

            # Changes
            ${{ steps.changelog.outputs.changelog }}
        files: ${{github.workspace}}/outputs/*.pkg

    - name: Upload packages
      uses: actions/upload-artifact@v3.1.1
      with:
        name: packages
        path: outputs/
