name: Build signed Nudge for pull requests

on:
  pull_request_target:
    types: [labeled]

jobs:
  build:
    runs-on: macos-12
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
    - name: Checkout nudge repo
      uses: actions/checkout@v3.2.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Install Apple Xcode certificates
      uses: ssrobins/import-codesign-certs@04ce695a5e6002f1971a8ed78fedd676318f950f # Move back to apple-actions/import-codesign-certs when merged
      with:
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        p12-file-base64: ${{ secrets.APP_CERTIFICATES_P12 }}
        p12-password: ${{ secrets.APP_CERTIFICATES_P12_PASSWORD }}

    - name: Install Apple Installer certificates
      uses: ssrobins/import-codesign-certs@04ce695a5e6002f1971a8ed78fedd676318f950f # Move back to apple-actions/import-codesign-certs when merged
      with:
        create-keychain: false # do not create a new keychain for this value
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        p12-file-base64: ${{ secrets.PKG_CERTIFICATES_P12 }}
        p12-password: ${{ secrets.PKG_CERTIFICATES_P12_PASSWORD }}

    - name: Run build package script
      run: ./build_nudge.zsh

    - name: get environment variables
      id: get_env_var
      run: |
         echo "NUDGE_VERSION=$(/bin/cat ./build_info.txt)" >> $GITHUB_ENV
         echo "NUDGE_MAIN_VERSION=$(/bin/cat ./build_info_main.txt)" >> $GITHUB_ENV

    - name: Upload packages
      uses: actions/upload-artifact@v3.1.1
      with:
        name: packages
        path: outputs/
